# Generated by Django 4.2.2 on 2023-06-08 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cusine', models.CharField(max_length=250)),
                ('cusineid', models.IntegerField(default=None, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inputf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('time_log', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('contact', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('reservation_date', models.DateField(default=django.utils.timezone.now)),
                ('reservation_slot', models.SmallIntegerField(default=10)),
                ('count', models.IntegerField(default=1, verbose_name='Number of People')),
                ('notes', models.CharField(max_length=650, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=750)),
                ('cusineid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ChefsTable_control.cuisine')),
            ],
        ),
    ]
